/**
 * Creates VBScript to extract ALL text data from ALL BarTender .btw files.
 * Robust error handling — skips files that fail.
 */
const fs = require('fs');
const path = require('path');

const vbsContent = [
  'Option Explicit',
  '',
  'Dim fso, shell, btApp, outFile, ts',
  'Set fso = CreateObject("Scripting.FileSystemObject")',
  'Set shell = CreateObject("WScript.Shell")',
  '',
  'outFile = shell.ExpandEnvironmentStrings("%USERPROFILE%") & "\\Desktop\\Rezograf_Agent\\rezograf\\btw_all_data.txt"',
  'Set ts = fso.CreateTextFile(outFile, True, True)',
  '',
  'Dim srcFolder',
  'srcFolder = shell.ExpandEnvironmentStrings("%USERPROFILE%") & "\\Desktop\\extracted_labels"',
  '',
  'ts.WriteLine "EXTRACTION_START"',
  '',
  'Dim btOK',
  'btOK = False',
  'On Error Resume Next',
  'Set btApp = CreateObject("BarTender.Application")',
  'If Err.Number = 0 Then',
  '    btOK = True',
  'Else',
  '    ts.WriteLine "FATAL_ERROR=" & Err.Description',
  'End If',
  'On Error GoTo 0',
  '',
  'If Not btOK Then',
  '    ts.Close',
  '    WScript.Quit 1',
  'End If',
  '',
  'Dim allFiles',
  'Set allFiles = CreateObject("Scripting.Dictionary")',
  'Call FindFiles(fso.GetFolder(srcFolder), allFiles)',
  'ts.WriteLine "TOTAL_FILES=" & allFiles.Count',
  '',
  'Dim keys, k, filePath, btFormat, obj, i, lineNum, successCount',
  'keys = allFiles.Keys',
  'lineNum = 0',
  'successCount = 0',
  '',
  'For Each k In keys',
  '    filePath = CStr(k)',
  '    lineNum = lineNum + 1',
  '    ',
  '    ts.WriteLine "FILE_START=" & filePath',
  '    ',
  '    On Error Resume Next',
  '    Err.Clear',
  '    Set btFormat = Nothing',
  '    Set btFormat = btApp.Formats.Open(filePath, False, "")',
  '    ',
  '    If Err.Number <> 0 Then',
  '        ts.WriteLine "OPEN_ERROR=" & Err.Description',
  '        Err.Clear',
  '        ts.WriteLine "FILE_END"',
  '        On Error GoTo 0',
  '    ElseIf btFormat Is Nothing Then',
  '        ts.WriteLine "OPEN_ERROR=format is Nothing"',
  '        ts.WriteLine "FILE_END"',
  '        On Error GoTo 0',
  '    Else',
  '        Err.Clear',
  '        ',
  '        Dim objCount',
  '        objCount = 0',
  '        If Not btFormat.Objects Is Nothing Then',
  '            objCount = btFormat.Objects.Count',
  '        End If',
  '        ts.WriteLine "OBJECTS_COUNT=" & objCount',
  '        ',
  '        For i = 1 To objCount',
  '            Err.Clear',
  '            Set obj = Nothing',
  '            Set obj = btFormat.Objects.Item(i)',
  '            If Not obj Is Nothing Then',
  '                Dim oName, oType, oVal',
  '                oName = ""',
  '                oType = ""',
  '                oVal = ""',
  '                oName = obj.Name',
  '                oType = obj.Type',
  '                oVal = obj.Value',
  '                If Err.Number <> 0 Then',
  '                    oVal = "(error: " & Err.Description & ")"',
  '                    Err.Clear',
  '                End If',
  '                oVal = Replace(Replace(oVal, vbCr, " "), vbLf, " ")',
  '                ts.WriteLine "OBJ|" & i & "|" & oName & "|" & oType & "|" & oVal',
  '            End If',
  '        Next',
  '        ',
  '        On Error GoTo 0',
  '        On Error Resume Next',
  '        btFormat.Close False',
  '        If Err.Number <> 0 Then Err.Clear',
  '        On Error GoTo 0',
  '        successCount = successCount + 1',
  '        ts.WriteLine "FILE_END"',
  '    End If',
  '    ',
  '    If lineNum Mod 100 = 0 Then',
  '        WScript.Echo "Progress: " & lineNum & " / " & allFiles.Count & " (" & successCount & " OK)"',
  '    End If',
  'Next',
  '',
  'On Error Resume Next',
  'btApp.Quit',
  'On Error GoTo 0',
  '',
  'ts.WriteLine "EXTRACTION_DONE=" & successCount & "/" & allFiles.Count',
  'ts.Close',
  'WScript.Echo "Done! " & successCount & "/" & allFiles.Count & " files extracted"',
  '',
  'Sub FindFiles(folder, dict)',
  '    Dim f, sf',
  '    On Error Resume Next',
  '    For Each f In folder.Files',
  '        If LCase(Right(f.Name, 4)) = ".btw" Then',
  '            dict.Add f.Path, f.Name',
  '        End If',
  '    Next',
  '    For Each sf In folder.SubFolders',
  '        FindFiles sf, dict',
  '    Next',
  '    On Error GoTo 0',
  'End Sub',
].join('\r\n');

const vbsPath = path.join(process.cwd(), 'btw_extract_all.vbs');
fs.writeFileSync(vbsPath, vbsContent, 'latin1');
console.log('VBS written to:', vbsPath);
console.log('Running extraction of ALL 1845 files...');
